### ISSUE TITLE
possible destroy method issue

### ISSUE THREAD

**Issue by nickmay** [timmywil/password123#4]
Hi

Thank you very much for adding the "destroy" method. Much appreciated. Unfortunately I am having trouble making it work reliably. I can "switch on" password123, but when I come to switch it off by invoking the destroy function (in the manner specified in your docs, I believe) it generates an error in jQuery 1.4.4. (and 1.5 I think....)

The error is:
TypeError: Result of expression 'a' [undefined] is not an object.

I have a bare bones install that displays the issue here:
http://dl.dropbox.com/u/1340008/password123/index.html

Am I using it correctly? Is this a genuine error or am I just being particularly bone-headed today?

Help much appreciated - and once again, thank you for all the work you do on this plugin.

regards 

Nick

**Comment by timmywil** [comment]
Great catch.  I did it the right way in my tests, but not in my docs.  You can see I have updated the docs here https://github.com/timmywil/password123/.  Since the fields are no longer password fields, doing $('input:password') is an empty selection, but you get the new fields back when you call password123, so all you have to do is save them out.

**Comment by timmywil** [comment]
Also, I made a fiddle when I was testing your problem.  http://jsfiddle.net/timmywil/g5Sex/4/

**Comment by nickmay** [comment]
Great! Works fine now. Thank you.
